<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
// Form untuk option bundle produk
?>

<?php /* @var $block \Magento\Bundle\Block\Catalog\Product\View\Type\Bundle\Option\Checkbox */ ?>
<!--?php /* @var $block_bundle Magento\Bundle\Block\Catalog\Product\View\Type\Bundle */ ? error tag-->
<?php $_option = $block->getOption() ?>
<!--?php $product = $block->getProduct() ?-->
<?php $_selections = $_option->getSelections() ?>
<div class="field option <?php echo ($_option->getRequired()) ? ' required': ''; ?>">
    <label class="label">
        <span><?php echo $block->escapeHtml($_option->getTitle()) ?></span>
    </label>
    <div class="control">
        <div class="nested options-list">
            <?php if ($block->showSingle()): ?>
                <?php /* @escapeNotVerified */ echo $block->getSelectionQtyTitlePrice($_selections[0]) ?>
                <input type="hidden"
                       class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>  product bundle option"
                       name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>]"
                       value="<?php /* @escapeNotVerified */ echo $_selections[0]->getSelectionId() ?>"/>
            <!--Tampilkan bundle item ketika tipe produk adalah bundle -->
            <?php else:?>
                <?php foreach($_selections as $_selection): ?>
                    <!-- jika qty di option bundle = 0 -->
                    <?php if (intval($block->getQtyOption($_selection)) != 0/*|| intval($block->getQtyProduct()) != 0*/) : ?>
                        <div class="field choice">
                            <input class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?> checkbox product bundle option change-container-classname"
                                   id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"
                                   type="checkbox"
                                   <?php
                                   // yang dibawah ini untuk data require aksesoris dan validasi data
                                   // cek juga javascript validasi data option/aksesoris
                                   ?>
                                   <?php if ($_option->getRequired()) echo 'data-validate="{\'validate-one-required-by-name\':\'input[name^=&quot;bundle_option[' . $_option->getId() . ']&quot;]:checked\'}"'?>
                                   name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>][<?php /* @escapeNotVerified */ echo $_selection->getId() ?>]"
                                   data-selector="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>][<?php /* @escapeNotVerified */ echo $_selection->getId() ?>]"
                                   <?php if ($block->isSelected($_selection)) echo ' checked="checked"' ?>
                                   <?php if (!$_selection->isSaleable()) echo ' disabled="disabled"' ?>
                                   value="<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"/>
                            <label class="label"
                                   for="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>">
                                <!--span>< ?php /* @escapeNotVerified */ echo $block->getSelectionQtyTitlePrice($_selection) ?></ . $block_bundle->getProduct()->getSku() -->
                                <span><?php /* @escapeNotVerified */ echo $block->getSelectionTitlePrice($_selection)?></span>
                                <!--span>< ?php /* @escapeNotVerified */ echo 'Disini nama produk bundle' ?></span-->
                            </label>
                            <input class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?> text product bundle option change-container-classname"
                                   id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-<?php /* @escapeNotVerified */ echo $_selection->getSelectionId() ?>"
                                   type="text" minlength="2" maxlength="4" size="4"
                                   name="bundle_option[<?php /* @escapeNotVerified */ echo $_option->getId() ?>][<?php /* @escapeNotVerified */ echo $_selection->getId() ?>]"
                                   value="<?php /* @escapeNotVerified */ echo intval($block->getQtyOption($_selection)) ?>"/>

                            <?php foreach ($block->getImageGallery() as $image) : ?>
                                <img class="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?> image product bundle option change-container-classname"
                                     style="width: 50px; height: 50px; margin-top: 5px"
                                     src="<?php echo $image->getUrl() ?>" /> <!-- gambar url/path -->
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
                <div id="bundle-option-<?php /* @escapeNotVerified */ echo $_option->getId() ?>-container"></div>
            <?php endif; ?>
        </div>
    </div>
</div>
